// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BarChart: typeof import('./src/components/echart/src/BarChart.vue')['default']
    BaseChart: typeof import('./src/components/echart/src/BaseChart.vue')['default']
    BaseSelect: typeof import('./src/components/pro-table/src/components/SearchForm/components/BaseSelect.vue')['default']
    ColSetting: typeof import('./src/components/pro-table/src/components/ColSetting.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Grid: typeof import('./src/components/pro-table/src/components/Grid/index.vue')['default']
    GridItem: typeof import('./src/components/pro-table/src/components/Grid/components/GridItem.vue')['default']
    LineChart: typeof import('./src/components/echart/src/LineChart.vue')['default']
    Pagination: typeof import('./src/components/pro-table/src/components/Pagination.vue')['default']
    PieChart: typeof import('./src/components/echart/src/PieChart.vue')['default']
    RemoteSelect: typeof import('./src/components/pro-table/src/components/SearchForm/components/RemoteSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./src/components/pro-table/src/components/SearchForm/index.vue')['default']
    SearchFormItem: typeof import('./src/components/pro-table/src/components/SearchForm/components/SearchFormItem.vue')['default']
    Src: typeof import('./src/components/echart/src/index.vue')['default']
    TableColumn: typeof import('./src/components/pro-table/src/components/TableColumn.vue')['default']
  }
}
